language: java
before_install:
- echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import --batch || true
- echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust --batch || true
jdk:
- openjdk8
- openjdk11
install:
- mvn --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true
  -B -V
after_success:
- bash <(curl -s https://codecov.io/bash) -t $CODECOV_KEY
deploy:
- provider: script
  script: mvn clean deploy --settings .maven.xml -DskipTests=true -B -U -Prelease
  skip_cleanup: true
  on:
    tags: true
    jdk: openjdk8
    branch: main
notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      secure: jnmSBE28sD/3ZFMDtnBtrxpB4h8aOPmqXJXv7rUQMUflf5+9slbaj8des72QpNAWOJnHjY0MasfKCuQlau9b5iPllJEF3aVswCORFErsLT3U5UW4qolC0MeTygj3g6RQUsrgFxuUxOrDW6OSkFV4gASyrFIqeI+pBj8Xu0YAdxnIJGTAKYQ+c8wLL4uiUgle3id0QRTv6BArezROjAlFpE7S40BCN/ulgVOT1X0gD3HtuXkSscnmnqmWY2UurbHQ3yPcR2xJo75tY6Hf4CxTJAqioVH8ygbboMMFYbzhlfZyGofbz01g5mUNRB6s39AnoxoOhkDJRJY6J3i+xhJBufLN8XxiFyq176ngZJDjCF/pjg5sWDdlmG8pHZawrBEecMOrg29CnuuBzNZpWz1+93cOD4Ak1UtZC5m04+X8oMUx1Q+pjRPdFJYSHXStBBYNV1/aNCNIOFVm6tAN+JgpO6I3aEKI2PMJaxeqUtU931pEzz/48DJYCHIsL7ZSDopPjenPck6UfhrwE4fubzwfac8JVnwTGKqENlVChPP7jMTb8tK2a2RpMel7PMrriTUm+RMoEFi8x2wntPm9CdqQ+bn8VsOppQ2IIOj85d4prcPxfTJMUsKAQh5WRHHT472WxH+OOOFYo6fZLEam+toTmW/zeK8+oCefVy+1SQR8hHk=
