language: java
before_install:
- echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import --batch || true
jdk:
- openjdk8
- openjdk11
install:
- mvn --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true
  -B -V
after_success:
- bash <(curl -s https://codecov.io/bash) -t $CODECOV_KEY
deploy:
- provider: script
  script: mvn clean deploy --settings .maven.xml -DskipTests=true -B -U -Prelease
  skip_cleanup: true
  on:
    tags: true
    jdk: openjdk8
    branch: main
notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      secure: Pk4BJvzEPXTTsXD5Q39BVPmEh3c6C0vhImWByUAmEwXI+y2qWG3gXlU9KzbdGTI/50bw3mfUkEzpH9wFlRa9A8zB1eAuyuC89S1JKtaKARuzaqw3yJYUh9YV9xmJ128I9/F7Zgnr22K0DxStQp+qunMP8n8YWsOsBh+RiiFGbx8X53JDT+rgzyTqAMbxWLqj4IZX8Fzdw54dMClob8zGkSRtkFoyaYV1rodrOucfK1pRFeCt7nsK2+4PaLIHNY1IPbK+M/aE0dn6A8FxWB2RAE83bqAOjPNDuZkWdkZYtnwZZXHhfQ/RNrQbMM6rKFvEuW+BtHD/zvm60dNgovJhx1oM9hqCBFTwgDIV6XdnROPpEsfB+DRcYubaUdJ2XHSOFVJDWDdTq01nf3AtpfGlXE0kufdiEFhgbBpFV2QYFxae5az+bLEQvpNkcsSd3NIETRKx5HqUNJ/3xQK12zfQTWF1VV/ugfvJuz5MrY84hvr3TRG0K3njevYtTbBa0EWHfH5dWnzdJXgrrNNVKqA9/o/349otINAXYg3h1b4CbYSyEJOnCPc6J553jgoVxm1lrNgTRNFWZ3IxR3GmK0CG2xDew6Nx4gbIGjK3+7W6GTN9xy6KcErU7MogcMNVcAk0hQ8jQDxenG65e8coGHmt+ZlIxpqyWq0bv8xlgmVWiAY=
